name: Build SecretScanner Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repository
      run: |
        git clone https://github.com/deepfence/SecretScanner.git
        cd SecretScanner
      shell: bash

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x # Use the Go version compatible with your project

    - name: Run Bootstrap Script and Build Docker Image
      run: |
        chmod +x ./bootstrap.sh
        ./bootstrap.sh
        docker build --rm=true --tag=toaeio/toae_secret_scanner:2.0.0 -f Dockerfile .

    - name: Push Docker Image to Docker Hub
      run: docker push toaeio/toae_secret_scanner:2.0.0
