name: Build and Run Fluent Bit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up CMake, Flex, Bison, and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake flex bison libyaml-dev libssl-dev

    - name: Clone Fluent Bit Repository
      run: |
        git clone https://github.com/Sam12121/fluent-bit.git
        cd fluent-bit

        # Check if CMakeLists.txt exists
        if [ ! -e "CMakeLists.txt" ]; then
          echo "Error: CMakeLists.txt not found in the fluent-bit directory."
          exit 1
        fi

        cmake ..
        make
        ./bin/fluent-bit -i cpu -o stdout -f 1
